### ISSUE TITLE
Add methods

### ISSUE THREAD

**Issue by Samoht70** [xefi/faker-php#38]
`faker()->boolean(30)` 
`faker()->randomElement(['sum', 'count'])`

On the old faker, there were 2 methods `boolean()` and `randomElement().` The `boolean()` method takes as an argument the chance of obtaining ‘true’ and the `randomElement()` method takes as an argument an array of values

**Comment by GautierDele** [comment]
Will be easy to add, coming soon 🚀

**Comment by Samoht70** [comment]
For locales add `company()` method to have name of companies

**Comment by Samoht70** [comment]
For locales add `address()` method to give complete postal address

**Comment by martinsoenen** [comment]
Also in person or internet we should add `mail()` or `email()` to give a random email address

**Comment by GautierDele** [comment]
Merged, thanks @martinsoenen
